VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThisDrawing"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Sub Combolijst1()

blokken.ComboBox1.AddItem "Badkamer"
blokken.ComboBox1.AddItem "Bedrijfsruimte1"
blokken.ComboBox1.AddItem "Bedrijfsruimte2"
blokken.ComboBox1.AddItem "Berging"
blokken.ComboBox1.AddItem "Bijkeuken"
blokken.ComboBox1.AddItem "Bureel"
blokken.ComboBox1.AddItem "Directiekamer"
blokken.ComboBox1.AddItem "Douche"
blokken.ComboBox1.AddItem "Eetkamer"
blokken.ComboBox1.AddItem "Entree"
blokken.ComboBox1.AddItem "Gang"
blokken.ComboBox1.AddItem "Garage"
blokken.ComboBox1.AddItem "Groepsruimte"
blokken.ComboBox1.AddItem "Groepsruimte1"
blokken.ComboBox1.AddItem "Groepsruimte2"
blokken.ComboBox1.AddItem "Hal"
blokken.ComboBox1.AddItem "Hobby"
blokken.ComboBox1.AddItem "Kantine"
blokken.ComboBox1.AddItem "Kantoor"
blokken.ComboBox1.AddItem "Kantoor1"
blokken.ComboBox1.AddItem "Kantoor2"
blokken.ComboBox1.AddItem "Keuken"
blokken.ComboBox1.AddItem "Opkamer"
blokken.ComboBox1.AddItem "Opslag"
blokken.ComboBox1.AddItem "Overloop"
blokken.ComboBox1.AddItem "Portaal"
blokken.ComboBox1.AddItem "Serre"
blokken.ComboBox1.AddItem "Slaapkamer"
blokken.ComboBox1.AddItem "Slaapkamer1"
blokken.ComboBox1.AddItem "Slaapkamer2"
blokken.ComboBox1.AddItem "Slaapkamer3"
blokken.ComboBox1.AddItem "Slaapkamer4"
blokken.ComboBox1.AddItem "Spoelkeuken"
blokken.ComboBox1.AddItem "Studeerkamer"
blokken.ComboBox1.AddItem "Toilet"
blokken.ComboBox1.AddItem "Tuinkamer"
blokken.ComboBox1.AddItem "Verblijfsruimte"
blokken.ComboBox1.AddItem "Verblijfsruimte1"
blokken.ComboBox1.AddItem "Verblijfsruimte2"
blokken.ComboBox1.AddItem "Verkoop"
blokken.ComboBox1.AddItem "Voorkamer"
blokken.ComboBox1.AddItem "W.C"
blokken.ComboBox1.AddItem "Werkkamer"
blokken.ComboBox1.AddItem "Winkel"
blokken.ComboBox1.AddItem "Woonkamer"
blokken.ComboBox1.AddItem "Zitkamer"
blokken.ComboBox1.AddItem "Zolder"
blokken.ComboBox1.AddItem "Zwembad"
blokken.ComboBox1.MatchEntry = fmMatchEntryFirstLetter
End Sub

Sub Combolijst2()

blokken.ComboBox2.AddItem "Badkamer"
blokken.ComboBox2.AddItem "Bedrijfsruimte1"
blokken.ComboBox2.AddItem "Bedrijfsruimte2"
blokken.ComboBox2.AddItem "Berging"
blokken.ComboBox2.AddItem "Bijkeuken"
blokken.ComboBox2.AddItem "Bureel"
blokken.ComboBox2.AddItem "Directiekamer"
blokken.ComboBox2.AddItem "Douche"
blokken.ComboBox2.AddItem "Eetkamer"
blokken.ComboBox2.AddItem "Entree"
blokken.ComboBox2.AddItem "Gang"
blokken.ComboBox2.AddItem "Garage"
blokken.ComboBox2.AddItem "Groepsruimte"
blokken.ComboBox2.AddItem "Groepsruimte1"
blokken.ComboBox2.AddItem "Groepsruimte2"
blokken.ComboBox2.AddItem "Hal"
blokken.ComboBox2.AddItem "Hobby"
blokken.ComboBox2.AddItem "Kantine"
blokken.ComboBox2.AddItem "Kantoor"
blokken.ComboBox2.AddItem "Kantoor1"
blokken.ComboBox2.AddItem "Kantoor2"
blokken.ComboBox2.AddItem "Keuken"
blokken.ComboBox2.AddItem "Opkamer"
blokken.ComboBox2.AddItem "Opslag"
blokken.ComboBox2.AddItem "Overloop"
blokken.ComboBox2.AddItem "Portaal"
blokken.ComboBox2.AddItem "Serre"
blokken.ComboBox2.AddItem "Slaapkamer"
blokken.ComboBox2.AddItem "Slaapkamer1"
blokken.ComboBox2.AddItem "Slaapkamer2"
blokken.ComboBox2.AddItem "Slaapkamer3"
blokken.ComboBox2.AddItem "Slaapkamer4"
blokken.ComboBox2.AddItem "Spoelkeuken"
blokken.ComboBox2.AddItem "Studeerkamer"
blokken.ComboBox2.AddItem "Toilet"
blokken.ComboBox2.AddItem "Tuinkamer"
blokken.ComboBox2.AddItem "Verblijfsruimte"
blokken.ComboBox2.AddItem "Verblijfsruimte1"
blokken.ComboBox2.AddItem "Verblijfsruimte2"
blokken.ComboBox2.AddItem "Verkoop"
blokken.ComboBox2.AddItem "Voorkamer"
blokken.ComboBox2.AddItem "W.C"
blokken.ComboBox2.AddItem "Werkkamer"
blokken.ComboBox2.AddItem "Winkel"
blokken.ComboBox2.AddItem "Woonkamer"
blokken.ComboBox2.AddItem "Zitkamer"
blokken.ComboBox2.AddItem "Zolder"
blokken.ComboBox2.AddItem "Zwembad"
blokken.ComboBox2.MatchEntry = fmMatchEntryFirstLetter
End Sub

Sub Combolijst3()

blokken.ComboBox3.AddItem "Badkamer"
blokken.ComboBox3.AddItem "Bedrijfsruimte1"
blokken.ComboBox3.AddItem "Bedrijfsruimte2"
blokken.ComboBox3.AddItem "Berging"
blokken.ComboBox3.AddItem "Bijkeuken"
blokken.ComboBox3.AddItem "Bureel"
blokken.ComboBox3.AddItem "Directiekamer"
blokken.ComboBox3.AddItem "Douche"
blokken.ComboBox3.AddItem "Eetkamer"
blokken.ComboBox3.AddItem "Entree"
blokken.ComboBox3.AddItem "Gang"
blokken.ComboBox3.AddItem "Garage"
blokken.ComboBox3.AddItem "Groepsruimte"
blokken.ComboBox3.AddItem "Groepsruimte1"
blokken.ComboBox3.AddItem "Groepsruimte2"
blokken.ComboBox3.AddItem "Hal"
blokken.ComboBox3.AddItem "Hobby"
blokken.ComboBox3.AddItem "Kantine"
blokken.ComboBox3.AddItem "Kantoor"
blokken.ComboBox3.AddItem "Kantoor1"
blokken.ComboBox3.AddItem "Kantoor2"
blokken.ComboBox3.AddItem "Keuken"
blokken.ComboBox3.AddItem "Opkamer"
blokken.ComboBox3.AddItem "Opslag"
blokken.ComboBox3.AddItem "Overloop"
blokken.ComboBox3.AddItem "Portaal"
blokken.ComboBox3.AddItem "Serre"
blokken.ComboBox3.AddItem "Slaapkamer"
blokken.ComboBox3.AddItem "Slaapkamer1"
blokken.ComboBox3.AddItem "Slaapkamer2"
blokken.ComboBox3.AddItem "Slaapkamer3"
blokken.ComboBox3.AddItem "Slaapkamer4"
blokken.ComboBox3.AddItem "Spoelkeuken"
blokken.ComboBox3.AddItem "Studeerkamer"
blokken.ComboBox3.AddItem "Toilet"
blokken.ComboBox3.AddItem "Tuinkamer"
blokken.ComboBox3.AddItem "Verblijfsruimte"
blokken.ComboBox3.AddItem "Verblijfsruimte1"
blokken.ComboBox3.AddItem "Verblijfsruimte2"
blokken.ComboBox3.AddItem "Verkoop"
blokken.ComboBox3.AddItem "Voorkamer"
blokken.ComboBox3.AddItem "W.C"
blokken.ComboBox3.AddItem "Werkkamer"
blokken.ComboBox3.AddItem "Winkel"
blokken.ComboBox3.AddItem "Woonkamer"
blokken.ComboBox3.AddItem "Zitkamer"
blokken.ComboBox3.AddItem "Zolder"
blokken.ComboBox3.AddItem "Zwembad"
blokken.ComboBox3.MatchEntry = fmMatchEntryFirstLetter
End Sub

Sub Combolijst4()

blokken.ComboBox4.AddItem "Badkamer"
blokken.ComboBox4.AddItem "Bedrijfsruimte1"
blokken.ComboBox4.AddItem "Bedrijfsruimte2"
blokken.ComboBox4.AddItem "Berging"
blokken.ComboBox4.AddItem "Bijkeuken"
blokken.ComboBox4.AddItem "Bureel"
blokken.ComboBox4.AddItem "Directiekamer"
blokken.ComboBox4.AddItem "Douche"
blokken.ComboBox4.AddItem "Eetkamer"
blokken.ComboBox4.AddItem "Entree"
blokken.ComboBox4.AddItem "Gang"
blokken.ComboBox4.AddItem "Garage"
blokken.ComboBox4.AddItem "Groepsruimte"
blokken.ComboBox4.AddItem "Groepsruimte1"
blokken.ComboBox4.AddItem "Groepsruimte2"
blokken.ComboBox4.AddItem "Hal"
blokken.ComboBox4.AddItem "Hobby"
blokken.ComboBox4.AddItem "Kantine"
blokken.ComboBox4.AddItem "Kantoor"
blokken.ComboBox4.AddItem "Kantoor1"
blokken.ComboBox4.AddItem "Kantoor2"
blokken.ComboBox4.AddItem "Keuken"
blokken.ComboBox4.AddItem "Opkamer"
blokken.ComboBox4.AddItem "Opslag"
blokken.ComboBox4.AddItem "Overloop"
blokken.ComboBox4.AddItem "Portaal"
blokken.ComboBox4.AddItem "Serre"
blokken.ComboBox4.AddItem "Slaapkamer"
blokken.ComboBox4.AddItem "Slaapkamer1"
blokken.ComboBox4.AddItem "Slaapkamer2"
blokken.ComboBox4.AddItem "Slaapkamer3"
blokken.ComboBox4.AddItem "Slaapkamer4"
blokken.ComboBox4.AddItem "Spoelkeuken"
blokken.ComboBox4.AddItem "Studeerkamer"
blokken.ComboBox4.AddItem "Toilet"
blokken.ComboBox4.AddItem "Tuinkamer"
blokken.ComboBox4.AddItem "Verblijfsruimte"
blokken.ComboBox4.AddItem "Verblijfsruimte1"
blokken.ComboBox4.AddItem "Verblijfsruimte2"
blokken.ComboBox4.AddItem "Verkoop"
blokken.ComboBox4.AddItem "Voorkamer"
blokken.ComboBox4.AddItem "W.C"
blokken.ComboBox4.AddItem "Werkkamer"
blokken.ComboBox4.AddItem "Winkel"
blokken.ComboBox4.AddItem "Woonkamer"
blokken.ComboBox4.AddItem "Zitkamer"
blokken.ComboBox4.AddItem "Zolder"
blokken.ComboBox4.AddItem "Zwembad"
blokken.ComboBox4.MatchEntry = fmMatchEntryFirstLetter
End Sub

Sub Combolijst5()

blokken.ComboBox5.AddItem "Badkamer"
blokken.ComboBox5.AddItem "Bedrijfsruimte1"
blokken.ComboBox5.AddItem "Bedrijfsruimte2"
blokken.ComboBox5.AddItem "Berging"
blokken.ComboBox5.AddItem "Bijkeuken"
blokken.ComboBox5.AddItem "Bureel"
blokken.ComboBox5.AddItem "Directiekamer"
blokken.ComboBox5.AddItem "Douche"
blokken.ComboBox5.AddItem "Eetkamer"
blokken.ComboBox5.AddItem "Entree"
blokken.ComboBox5.AddItem "Gang"
blokken.ComboBox5.AddItem "Garage"
blokken.ComboBox5.AddItem "Groepsruimte"
blokken.ComboBox5.AddItem "Groepsruimte1"
blokken.ComboBox5.AddItem "Groepsruimte2"
blokken.ComboBox5.AddItem "Hal"
blokken.ComboBox5.AddItem "Hobby"
blokken.ComboBox5.AddItem "Kantine"
blokken.ComboBox5.AddItem "Kantoor"
blokken.ComboBox5.AddItem "Kantoor1"
blokken.ComboBox5.AddItem "Kantoor2"
blokken.ComboBox5.AddItem "Keuken"
blokken.ComboBox5.AddItem "Opkamer"
blokken.ComboBox5.AddItem "Opslag"
blokken.ComboBox5.AddItem "Overloop"
blokken.ComboBox5.AddItem "Portaal"
blokken.ComboBox5.AddItem "Serre"
blokken.ComboBox5.AddItem "Slaapkamer"
blokken.ComboBox5.AddItem "Slaapkamer1"
blokken.ComboBox5.AddItem "Slaapkamer2"
blokken.ComboBox5.AddItem "Slaapkamer3"
blokken.ComboBox5.AddItem "Slaapkamer4"
blokken.ComboBox5.AddItem "Spoelkeuken"
blokken.ComboBox5.AddItem "Studeerkamer"
blokken.ComboBox5.AddItem "Toilet"
blokken.ComboBox5.AddItem "Tuinkamer"
blokken.ComboBox5.AddItem "Verblijfsruimte"
blokken.ComboBox5.AddItem "Verblijfsruimte1"
blokken.ComboBox5.AddItem "Verblijfsruimte2"
blokken.ComboBox5.AddItem "Verkoop"
blokken.ComboBox5.AddItem "Voorkamer"
blokken.ComboBox5.AddItem "W.C"
blokken.ComboBox5.AddItem "Werkkamer"
blokken.ComboBox5.AddItem "Winkel"
blokken.ComboBox5.AddItem "Woonkamer"
blokken.ComboBox5.AddItem "Zitkamer"
blokken.ComboBox5.AddItem "Zolder"
blokken.ComboBox5.AddItem "Zwembad"
blokken.ComboBox5.MatchEntry = fmMatchEntryFirstLetter
End Sub

Sub Combolijst6()

blokken.ComboBox6.AddItem "Badkamer"
blokken.ComboBox6.AddItem "Bedrijfsruimte1"
blokken.ComboBox6.AddItem "Bedrijfsruimte2"
blokken.ComboBox6.AddItem "Berging"
blokken.ComboBox6.AddItem "Bijkeuken"
blokken.ComboBox6.AddItem "Bureel"
blokken.ComboBox6.AddItem "Directiekamer"
blokken.ComboBox6.AddItem "Douche"
blokken.ComboBox6.AddItem "Eetkamer"
blokken.ComboBox6.AddItem "Entree"
blokken.ComboBox6.AddItem "Gang"
blokken.ComboBox6.AddItem "Garage"
blokken.ComboBox6.AddItem "Groepsruimte"
blokken.ComboBox6.AddItem "Groepsruimte1"
blokken.ComboBox6.AddItem "Groepsruimte2"
blokken.ComboBox6.AddItem "Hal"
blokken.ComboBox6.AddItem "Hobby"
blokken.ComboBox6.AddItem "Kantine"
blokken.ComboBox6.AddItem "Kantoor"
blokken.ComboBox6.AddItem "Kantoor1"
blokken.ComboBox6.AddItem "Kantoor2"
blokken.ComboBox6.AddItem "Keuken"
blokken.ComboBox6.AddItem "Opkamer"
blokken.ComboBox6.AddItem "Opslag"
blokken.ComboBox6.AddItem "Overloop"
blokken.ComboBox6.AddItem "Portaal"
blokken.ComboBox6.AddItem "Serre"
blokken.ComboBox6.AddItem "Slaapkamer"
blokken.ComboBox6.AddItem "Slaapkamer1"
blokken.ComboBox6.AddItem "Slaapkamer2"
blokken.ComboBox6.AddItem "Slaapkamer3"
blokken.ComboBox6.AddItem "Slaapkamer4"
blokken.ComboBox6.AddItem "Spoelkeuken"
blokken.ComboBox6.AddItem "Studeerkamer"
blokken.ComboBox6.AddItem "Toilet"
blokken.ComboBox6.AddItem "Tuinkamer"
blokken.ComboBox6.AddItem "Verblijfsruimte"
blokken.ComboBox6.AddItem "Verblijfsruimte1"
blokken.ComboBox6.AddItem "Verblijfsruimte2"
blokken.ComboBox6.AddItem "Verkoop"
blokken.ComboBox6.AddItem "Voorkamer"
blokken.ComboBox6.AddItem "W.C"
blokken.ComboBox6.AddItem "Werkkamer"
blokken.ComboBox6.AddItem "Winkel"
blokken.ComboBox6.AddItem "Woonkamer"
blokken.ComboBox6.AddItem "Zitkamer"
blokken.ComboBox6.AddItem "Zolder"
blokken.ComboBox6.AddItem "Zwembad"
blokken.ComboBox6.MatchEntry = fmMatchEntryFirstLetter
End Sub

Sub Combolijst7()

blokken.ComboBox7.AddItem "Badkamer"
blokken.ComboBox7.AddItem "Bedrijfsruimte1"
blokken.ComboBox7.AddItem "Bedrijfsruimte2"
blokken.ComboBox7.AddItem "Berging"
blokken.ComboBox7.AddItem "Bijkeuken"
blokken.ComboBox7.AddItem "Bureel"
blokken.ComboBox7.AddItem "Directiekamer"
blokken.ComboBox7.AddItem "Douche"
blokken.ComboBox7.AddItem "Eetkamer"
blokken.ComboBox7.AddItem "Entree"
blokken.ComboBox7.AddItem "Gang"
blokken.ComboBox7.AddItem "Garage"
blokken.ComboBox7.AddItem "Groepsruimte"
blokken.ComboBox7.AddItem "Groepsruimte1"
blokken.ComboBox7.AddItem "Groepsruimte2"
blokken.ComboBox7.AddItem "Hal"
blokken.ComboBox7.AddItem "Hobby"
blokken.ComboBox7.AddItem "Kantine"
blokken.ComboBox7.AddItem "Kantoor"
blokken.ComboBox7.AddItem "Kantoor1"
blokken.ComboBox7.AddItem "Kantoor2"
blokken.ComboBox7.AddItem "Keuken"
blokken.ComboBox7.AddItem "Opkamer"
blokken.ComboBox7.AddItem "Opslag"
blokken.ComboBox7.AddItem "Overloop"
blokken.ComboBox7.AddItem "Portaal"
blokken.ComboBox7.AddItem "Serre"
blokken.ComboBox7.AddItem "Slaapkamer"
blokken.ComboBox7.AddItem "Slaapkamer1"
blokken.ComboBox7.AddItem "Slaapkamer2"
blokken.ComboBox7.AddItem "Slaapkamer3"
blokken.ComboBox7.AddItem "Slaapkamer4"
blokken.ComboBox7.AddItem "Spoelkeuken"
blokken.ComboBox7.AddItem "Studeerkamer"
blokken.ComboBox7.AddItem "Toilet"
blokken.ComboBox7.AddItem "Tuinkamer"
blokken.ComboBox7.AddItem "Verblijfsruimte"
blokken.ComboBox7.AddItem "Verblijfsruimte1"
blokken.ComboBox7.AddItem "Verblijfsruimte2"
blokken.ComboBox7.AddItem "Verkoop"
blokken.ComboBox7.AddItem "Voorkamer"
blokken.ComboBox7.AddItem "W.C"
blokken.ComboBox7.AddItem "Werkkamer"
blokken.ComboBox7.AddItem "Winkel"
blokken.ComboBox7.AddItem "Woonkamer"
blokken.ComboBox7.AddItem "Zitkamer"
blokken.ComboBox7.AddItem "Zolder"
blokken.ComboBox7.AddItem "Zwembad"
blokken.ComboBox7.MatchEntry = fmMatchEntryFirstLetter
End Sub

Sub Combolijst8()

blokken.ComboBox8.AddItem "Badkamer"
blokken.ComboBox8.AddItem "Bedrijfsruimte1"
blokken.ComboBox8.AddItem "Bedrijfsruimte2"
blokken.ComboBox8.AddItem "Berging"
blokken.ComboBox8.AddItem "Bijkeuken"
blokken.ComboBox8.AddItem "Bureel"
blokken.ComboBox8.AddItem "Directiekamer"
blokken.ComboBox8.AddItem "Douche"
blokken.ComboBox8.AddItem "Eetkamer"
blokken.ComboBox8.AddItem "Entree"
blokken.ComboBox8.AddItem "Gang"
blokken.ComboBox8.AddItem "Garage"
blokken.ComboBox8.AddItem "Groepsruimte"
blokken.ComboBox8.AddItem "Groepsruimte1"
blokken.ComboBox8.AddItem "Groepsruimte2"
blokken.ComboBox8.AddItem "Hal"
blokken.ComboBox8.AddItem "Hobby"
blokken.ComboBox8.AddItem "Kantine"
blokken.ComboBox8.AddItem "Kantoor"
blokken.ComboBox8.AddItem "Kantoor1"
blokken.ComboBox8.AddItem "Kantoor2"
blokken.ComboBox8.AddItem "Keuken"
blokken.ComboBox8.AddItem "Opkamer"
blokken.ComboBox8.AddItem "Opslag"
blokken.ComboBox8.AddItem "Overloop"
blokken.ComboBox8.AddItem "Portaal"
blokken.ComboBox8.AddItem "Serre"
blokken.ComboBox8.AddItem "Slaapkamer"
blokken.ComboBox8.AddItem "Slaapkamer1"
blokken.ComboBox8.AddItem "Slaapkamer2"
blokken.ComboBox8.AddItem "Slaapkamer3"
blokken.ComboBox8.AddItem "Slaapkamer4"
blokken.ComboBox8.AddItem "Spoelkeuken"
blokken.ComboBox8.AddItem "Studeerkamer"
blokken.ComboBox8.AddItem "Toilet"
blokken.ComboBox8.AddItem "Tuinkamer"
blokken.ComboBox8.AddItem "Verblijfsruimte"
blokken.ComboBox8.AddItem "Verblijfsruimte1"
blokken.ComboBox8.AddItem "Verblijfsruimte2"
blokken.ComboBox8.AddItem "Verkoop"
blokken.ComboBox8.AddItem "Voorkamer"
blokken.ComboBox8.AddItem "W.C"
blokken.ComboBox8.AddItem "Werkkamer"
blokken.ComboBox8.AddItem "Winkel"
blokken.ComboBox8.AddItem "Woonkamer"
blokken.ComboBox8.AddItem "Zitkamer"
blokken.ComboBox8.AddItem "Zolder"
blokken.ComboBox8.AddItem "Zwembad"
blokken.ComboBox8.MatchEntry = fmMatchEntryFirstLetter
End Sub

Sub Combolijst9()

blokken.ComboBox9.AddItem "Badkamer"
blokken.ComboBox9.AddItem "Bedrijfsruimte1"
blokken.ComboBox9.AddItem "Bedrijfsruimte2"
blokken.ComboBox9.AddItem "Berging"
blokken.ComboBox9.AddItem "Bijkeuken"
blokken.ComboBox9.AddItem "Bureel"
blokken.ComboBox9.AddItem "Directiekamer"
blokken.ComboBox9.AddItem "Douche"
blokken.ComboBox9.AddItem "Eetkamer"
blokken.ComboBox9.AddItem "Entree"
blokken.ComboBox9.AddItem "Gang"
blokken.ComboBox9.AddItem "Garage"
blokken.ComboBox9.AddItem "Groepsruimte"
blokken.ComboBox9.AddItem "Groepsruimte1"
blokken.ComboBox9.AddItem "Groepsruimte2"
blokken.ComboBox9.AddItem "Hal"
blokken.ComboBox9.AddItem "Hobby"
blokken.ComboBox9.AddItem "Kantine"
blokken.ComboBox9.AddItem "Kantoor"
blokken.ComboBox9.AddItem "Kantoor1"
blokken.ComboBox9.AddItem "Kantoor2"
blokken.ComboBox9.AddItem "Keuken"
blokken.ComboBox9.AddItem "Opkamer"
blokken.ComboBox9.AddItem "Opslag"
blokken.ComboBox9.AddItem "Overloop"
blokken.ComboBox9.AddItem "Portaal"
blokken.ComboBox9.AddItem "Serre"
blokken.ComboBox9.AddItem "Slaapkamer"
blokken.ComboBox9.AddItem "Slaapkamer1"
blokken.ComboBox9.AddItem "Slaapkamer2"
blokken.ComboBox9.AddItem "Slaapkamer3"
blokken.ComboBox9.AddItem "Slaapkamer4"
blokken.ComboBox9.AddItem "Spoelkeuken"
blokken.ComboBox9.AddItem "Studeerkamer"
blokken.ComboBox9.AddItem "Toilet"
blokken.ComboBox9.AddItem "Tuinkamer"
blokken.ComboBox9.AddItem "Verblijfsruimte"
blokken.ComboBox9.AddItem "Verblijfsruimte1"
blokken.ComboBox9.AddItem "Verblijfsruimte2"
blokken.ComboBox9.AddItem "Verkoop"
blokken.ComboBox9.AddItem "Voorkamer"
blokken.ComboBox9.AddItem "W.C"
blokken.ComboBox9.AddItem "Werkkamer"
blokken.ComboBox9.AddItem "Winkel"
blokken.ComboBox9.AddItem "Woonkamer"
blokken.ComboBox9.AddItem "Zitkamer"
blokken.ComboBox9.AddItem "Zolder"
blokken.ComboBox9.AddItem "Zwembad"
blokken.ComboBox9.MatchEntry = fmMatchEntryFirstLetter
End Sub
Sub imagelijst1()
    MontageblokForm.Image1.Visible = False
    MontageblokForm.Image2.Visible = False
    MontageblokForm.Image3.Visible = False
    MontageblokForm.Image4.Visible = False
    MontageblokForm.Image5.Visible = False
    MontageblokForm.Image6.Visible = False
    MontageblokForm.Image7.Visible = False
    MontageblokForm.Image8.Visible = False
    MontageblokForm.Image9.Visible = False
    MontageblokForm.Image10.Visible = False
    MontageblokForm.Image11.Visible = False
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
    groepinvoerBox1.SetFocus
    PlaatsButton.Enabled = False
End Sub
Sub imagelijst2()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = False
    MontageblokForm.Image3.Visible = False
    MontageblokForm.Image4.Visible = False
    MontageblokForm.Image5.Visible = False
    MontageblokForm.Image6.Visible = False
    MontageblokForm.Image7.Visible = False
    MontageblokForm.Image8.Visible = False
    MontageblokForm.Image9.Visible = False
    MontageblokForm.Image10.Visible = False
    MontageblokForm.Image11.Visible = False
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst3()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = False
    MontageblokForm.Image4.Visible = False
    MontageblokForm.Image5.Visible = False
    MontageblokForm.Image6.Visible = False
    MontageblokForm.Image7.Visible = False
    MontageblokForm.Image8.Visible = False
    MontageblokForm.Image9.Visible = False
    MontageblokForm.Image10.Visible = False
    MontageblokForm.Image11.Visible = False
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst4()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = False
    MontageblokForm.Image5.Visible = False
    MontageblokForm.Image6.Visible = False
    MontageblokForm.Image7.Visible = False
    MontageblokForm.Image8.Visible = False
    MontageblokForm.Image9.Visible = False
    MontageblokForm.Image10.Visible = False
    MontageblokForm.Image11.Visible = False
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst5()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = False
    MontageblokForm.Image6.Visible = False
    MontageblokForm.Image7.Visible = False
    MontageblokForm.Image8.Visible = False
    MontageblokForm.Image9.Visible = False
    MontageblokForm.Image10.Visible = False
    MontageblokForm.Image11.Visible = False
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst6()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = False
    MontageblokForm.Image7.Visible = False
    MontageblokForm.Image8.Visible = False
    MontageblokForm.Image9.Visible = False
    MontageblokForm.Image10.Visible = False
    MontageblokForm.Image11.Visible = False
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst7()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = False
    MontageblokForm.Image8.Visible = False
    MontageblokForm.Image9.Visible = False
    MontageblokForm.Image10.Visible = False
    MontageblokForm.Image11.Visible = False
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst8()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = False
    MontageblokForm.Image9.Visible = False
    MontageblokForm.Image10.Visible = False
    MontageblokForm.Image11.Visible = False
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst9()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = False
    MontageblokForm.Image10.Visible = False
    MontageblokForm.Image11.Visible = False
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst10()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = False
    MontageblokForm.Image11.Visible = False
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst11()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = True
    MontageblokForm.Image11.Visible = False
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst12()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = True
    MontageblokForm.Image11.Visible = True
    MontageblokForm.Image12.Visible = False
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst13()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = True
    MontageblokForm.Image11.Visible = True
    MontageblokForm.Image12.Visible = True
    MontageblokForm.Image13.Visible = False
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst14()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = True
    MontageblokForm.Image11.Visible = True
    MontageblokForm.Image12.Visible = True
    MontageblokForm.Image13.Visible = True
    MontageblokForm.Image14.Visible = False
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst15()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = True
    MontageblokForm.Image11.Visible = True
    MontageblokForm.Image12.Visible = True
    MontageblokForm.Image13.Visible = True
    MontageblokForm.Image14.Visible = True
    MontageblokForm.Image15.Visible = False
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst16()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = True
    MontageblokForm.Image11.Visible = True
    MontageblokForm.Image12.Visible = True
    MontageblokForm.Image13.Visible = True
    MontageblokForm.Image14.Visible = True
    MontageblokForm.Image15.Visible = True
    MontageblokForm.Image16.Visible = False
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst17()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = True
    MontageblokForm.Image11.Visible = True
    MontageblokForm.Image12.Visible = True
    MontageblokForm.Image13.Visible = True
    MontageblokForm.Image14.Visible = True
    MontageblokForm.Image15.Visible = True
    MontageblokForm.Image16.Visible = True
    MontageblokForm.Image17.Visible = False
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst18()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = True
    MontageblokForm.Image11.Visible = True
    MontageblokForm.Image12.Visible = True
    MontageblokForm.Image13.Visible = True
    MontageblokForm.Image14.Visible = True
    MontageblokForm.Image15.Visible = True
    MontageblokForm.Image16.Visible = True
    MontageblokForm.Image17.Visible = True
    MontageblokForm.Image18.Visible = False
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst19()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = True
    MontageblokForm.Image11.Visible = True
    MontageblokForm.Image12.Visible = True
    MontageblokForm.Image13.Visible = True
    MontageblokForm.Image14.Visible = True
    MontageblokForm.Image15.Visible = True
    MontageblokForm.Image16.Visible = True
    MontageblokForm.Image17.Visible = True
    MontageblokForm.Image18.Visible = True
    MontageblokForm.Image19.Visible = False
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst20()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = True
    MontageblokForm.Image11.Visible = True
    MontageblokForm.Image12.Visible = True
    MontageblokForm.Image13.Visible = True
    MontageblokForm.Image14.Visible = True
    MontageblokForm.Image15.Visible = True
    MontageblokForm.Image16.Visible = True
    MontageblokForm.Image17.Visible = True
    MontageblokForm.Image18.Visible = True
    MontageblokForm.Image19.Visible = True
    MontageblokForm.Image20.Visible = False
End Sub
Sub imagelijst21()
    MontageblokForm.Image1.Visible = True
    MontageblokForm.Image2.Visible = True
    MontageblokForm.Image3.Visible = True
    MontageblokForm.Image4.Visible = True
    MontageblokForm.Image5.Visible = True
    MontageblokForm.Image6.Visible = True
    MontageblokForm.Image7.Visible = True
    MontageblokForm.Image8.Visible = True
    MontageblokForm.Image9.Visible = True
    MontageblokForm.Image10.Visible = True
    MontageblokForm.Image11.Visible = True
    MontageblokForm.Image12.Visible = True
    MontageblokForm.Image13.Visible = True
    MontageblokForm.Image14.Visible = True
    MontageblokForm.Image15.Visible = True
    MontageblokForm.Image16.Visible = True
    MontageblokForm.Image17.Visible = True
    MontageblokForm.Image18.Visible = True
    MontageblokForm.Image19.Visible = True
    MontageblokForm.Image20.Visible = True
End Sub
